trigger:
  branches:
    include:
      - main

pool:
  name: Agent_Pool  # Utilise votre pool d’agents personnalisé

steps:
  # Étape : Valider le déploiement en vérifiant l'accessibilité de l'application sur les VMs
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'pay_as_you_go'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # IP des machines virtuelles
        $VM1_IP = "172.203.225.108"
        $VM2_IP = "20.121.129.244"
        $APP_PORT = "8080"  # Le port sur lequel l'application Java est censée fonctionner
        
        Write-Host "Vérification de l'accès HTTP à l'application sur les VMs..."

        # Vérifier si l'application est accessible sur VM1
        try {
          $response1 = Invoke-WebRequest -Uri "http://${VM1_IP}:${APP_PORT}" -UseBasicParsing
          Write-Host "Application accessible sur VM1 : $($response1.StatusCode)"
        } catch {
          Write-Host "Erreur : Application non accessible sur VM1"
          exit 1
        }

        # Vérifier si l'application est accessible sur VM2
        try {
          $response2 = Invoke-WebRequest -Uri "http://${VM2_IP}:${APP_PORT}" -UseBasicParsing
          Write-Host "Application accessible sur VM2 : $($response2.StatusCode)"
        } catch {
          Write-Host "Erreur : Application non accessible sur VM2"
          exit 1
        }

        Write-Host "Vérification HTTP du déploiement terminée avec succès."
