trigger:
  branches:
    include:
      - main

pool:
  name: Agent_Pool  # Utilise votre pool d’agents personnalisé

steps:
   # Étape 1 : Transférer les fichiers de l’application sur les machines virtuelles
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'pay_as_you_go'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Variables de déploiement
        $RESOURCE_GROUP="rg-interstellar-havoc"
        $VM1_IP="172.203.225.108"
        $VM2_IP="20.121.129.244"
        $APP_PATH="/opt/java-app"  # Emplacement cible sur les VMs
        $SOURCE_PATH="$(System.DefaultWorkingDirectory)"  # Répertoire actuel du pipeline où se trouve l'application

        echo "Déploiement de l’application Java sur les machines virtuelles..."

        # Transférer les fichiers de l’application sur VM1 et VM2
        scp -r ${SOURCE_PATH}/* user@${VM1_IP}:${APP_PATH}
        scp -r ${SOURCE_PATH}/* user@${VM2_IP}:${APP_PATH}

        echo "Démarrage de l'application Java sur les VMs..."

        # Démarrer l'application sur chaque VM
        ssh user@${VM1_IP} "nohup java -jar ${APP_PATH}/nom-du-fichier.jar > /dev/null 2>&1 &"
        ssh user@${VM2_IP} "nohup java -jar ${APP_PATH}/nom-du-fichier.jar > /dev/null 2>&1 &"

        echo "Déploiement terminé."
