trigger:
  branches:
    include:
      - feature-pipeline

pool:
  name: Agent_Pool

steps:
  # Étape 1 : Vérification de l'accessibilité du fichier index.php via HTTP
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'pay_as_you_go'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Adresses IP des VMs où l'application doit être accessible via HTTP
        $IP_VM1 = "172.203.225.108"
        $IP_VM2 = "20.121.129.244"
        $MAIN_FILE = "index.php"  # Fichier principal à vérifier

        Write-Host "Vérification de l'accès à $MAIN_FILE via HTTP sur les VMs..."

        try {
          $response1 = Invoke-WebRequest -Uri "http://$IP_VM1/$MAIN_FILE" -UseBasicParsing -ErrorAction Stop
          Write-Host "Réponse de VM1 : $($response1.StatusCode)"
        } catch {
          Write-Host "Erreur lors de l'accès à $MAIN_FILE sur VM1 : $_"
        }

        try {
          $response2 = Invoke-WebRequest -Uri "http://$IP_VM2/$MAIN_FILE" -UseBasicParsing -ErrorAction Stop
          Write-Host "Réponse de VM2 : $($response2.StatusCode)"
        } catch {
          Write-Host "Erreur lors de l'accès à $MAIN_FILE sur VM2 : $_"
        }
